DROP VIEW IF EXISTS `whitelist`;
DROP TABLE IF EXISTS `imap_flag`;
DROP TABLE IF EXISTS `header`;
DROP TABLE IF EXISTS `mail_to`;
DROP TABLE IF EXISTS `mail_from`;
DROP TABLE IF EXISTS `mail_cc`;
DROP TABLE IF EXISTS `mail_bc`;
DROP TABLE IF EXISTS `mail_bcc`;
DROP TABLE IF EXISTS `record`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `db_ver`;

